### ISSUE TITLE
Upgrade or new install fail

### ISSUE THREAD

**Issue by Rudtran** [nolanlawson/pinafore#131]
The version v0.2.0 doesn't start : 

```
pinafore@pinafore:~$ git clone https://github.com/nolanlawson/pinafore.git
Clonage dans 'pinafore'...
remote: Counting objects: 8011, done.
remote: Total 8011 (delta 0), reused 0 (delta 0), pack-reused 8011
Réception d'objets: 100% (8011/8011), 123.69 MiB | 9.25 MiB/s, fait.
Résolution des deltas: 100% (6107/6107), fait.
pinafore@VM_mastodon:~$ cd pinafore/
pinafore@VM_mastodon:~/pinafore$ npm install

> node-sass@4.7.2 install /home/pinafore/pinafore/node_modules/node-sass
> node scripts/install.js

Cached binary found at /home/pinafore/.npm/node-sass/4.7.2/linux-x64-57_binding.node

> node-sass@4.7.2 postinstall /home/pinafore/pinafore/node_modules/node-sass
> node scripts/build.js

Binary found at /home/pinafore/pinafore/node_modules/node-sass/vendor/linux-x64-57/binding.node
Testing binary
Binary is fine

> now@11.1.4 postinstall /home/pinafore/pinafore/node_modules/now
> node download/install.js

> For the source code, check out: https://github.com/zeit/now-cli

> Downloading Now CLI 11.1.4 [====================] 100%

npm WARN pinafore@0.2.0 No repository field.
npm WARN pinafore@0.2.0 No license field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

added 1241 packages from 845 contributors in 24.917s
pinafore@pinafore:~/pinafore$ node server.js &
[1] 26366
pinafore@pinafore:~/pinafore$ module.js:549
    throw err;
    ^

Error: Cannot find module './inline-script-checksum'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/pinafore/pinafore/server.js:8:28)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3

[1]+  Termine 1               node server.js

```

On a lxc container with Debian 9.4, certainly in rapport with this commit : 
https://github.com/nolanlawson/pinafore/commit/283bc78b4f0cb593de01c81ef5a5e3e3a2a28783

Any ideas ?

**Comment by Rudtran** [comment]
ok, need to run with : npm run dev

**Comment by nolanlawson** [comment]
That's for dev mode. For production mode, you can run:

```
npm install
npm run build
npm start
```

This is documented in [CONTRIBUTING.md](https://github.com/nolanlawson/pinafore/blob/master/CONTRIBUTING.md)

**Comment by nolanlawson** [comment]
On second thought, I moved this to README.md so that it's easier to find.
