### ISSUE TITLE
TypeError: Intl.RelativeTimeFormat is not a constructor in node v10

### ISSUE THREAD

**Issue by ioistired** [nolanlawson/pinafore#2024]
```
> Crawling http://localhost:22939/
/var/lib/pinafore/app/__sapper__/build/server/server.js:1
TypeError: Intl.RelativeTimeFormat is not a constructor
    at Object.8413 (/var/lib/pinafore/app/__sapper__/build/server/server.js:8485:20)
    at __webpack_require__ (/var/lib/pinafore/app/__sapper__/build/server/server.js:30810:41)
    at Object.3273 (/var/lib/pinafore/app/__sapper__/build/server/server.js:4989:14)
    at __webpack_require__ (/var/lib/pinafore/app/__sapper__/build/server/server.js:30810:41)
    at Object.5341 (/var/lib/pinafore/app/__sapper__/build/server/server.js:10294:26)
    at __webpack_require__ (/var/lib/pinafore/app/__sapper__/build/server/server.js:30810:41)
    at /var/lib/pinafore/app/__sapper__/build/server/server.js:31015:19
    at /var/lib/pinafore/app/__sapper__/build/server/server.js:33826:3
    at Object.<anonymous> (/var/lib/pinafore/app/__sapper__/build/server/server.js:33829:12)
> timed out waiting for connection
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
ERROR: "sapper-export" exited with 1.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
ERROR: "build-steps" exited with 1.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

node v10.24.0, pinafore v1.24.0

**Comment by nolanlawson** [comment]
Thanks yup, looks like I accidentally broke Node 10 support. Sorry!

**Comment by nolanlawson** [comment]
BTW in case it's not clear: you can upgrade to Node 12 to fix this. But I'm trying to fix Node 10 support.

**Comment by ioistired** [comment]
Yep, I've been using Node v15 on my laptop to compile it and copying it over as of late. Previously though I was compiling with node v10 on Debian 10 (after all, Node v8 is the officially supported minimum version).

Anyway thanks, this fixed it.

**Comment by joenepraat** [comment]
Thanks @nolanlawson. I have Node 10 on this server, because I also have some other things running here (like Mastodon). Upgrading to Node 12 is probably a good idea, but out of experience I know that this can be tricky. So I need to do this carefully when I have the time.
