### ISSUE TITLE
Docker does not build

### ISSUE THREAD

**Issue by k3tan172** [nolanlawson/pinafore#2096]
Fresh installation of docker and docker-compose does not build. Output listed below. Ubuntu 20.04.

```
Creating network "pinafore_default" with the default driver
Building pinafore
Sending build context to Docker daemon  14.91MB
Step 1/6 : FROM node:alpine
alpine: Pulling from library/node
97518928ae5f: Pull complete 
a2af70dcde7d: Pull complete 
80e05fd95fdd: Pull complete 
1391c8a04394: Pull complete 
Digest: sha256:4522cc108ad7c055b71f545596bfc07632d9f9a41125ea12eabe8f04114807f3
Status: Downloaded newer image for node:alpine
 ---> e32df7d6c22c
Step 2/6 : WORKDIR /app
 ---> Running in 4b237786d75b
Removing intermediate container 4b237786d75b
 ---> 2f98f7b28f0a
Step 3/6 : COPY . /app
 ---> 05648789d6a9
Step 4/6 : RUN yarn --production --pure-lockfile &&     yarn build &&     yarn cache clean &&     rm -rf ./src ./docs ./tests ./bin
 ---> Running in 0cfd361f68a4
yarn install v1.22.17
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
[4/5] Linking dependencies...
warning "fake-indexeddb > realistic-structured-clone > typeson@5.18.2" has unmet peer dependency "core-js-bundle@^3.6.4".
warning "fake-indexeddb > realistic-structured-clone > typeson@5.18.2" has unmet peer dependency "regenerator-runtime@^0.13.3".
[5/5] Building fresh packages...
Done in 27.41s.
yarn run v1.22.17
$ cross-env NODE_ENV=production run-s build-steps
$ run-s before-build sapper-export build-vercel-json
$ run-p build-template-html build-assets build-webpack-config
$ node ./bin/build-template-html.js
$ node ./bin/build-assets.js
$ rollup -c ./webpack/rollup.config.js

./webpack/webpack.config.js → ./webpack/webpack.config.cjs...
created ./webpack/webpack.config.cjs in 192ms

./webpack/svelte-intl-loader.js → ./webpack/svelte-intl-loader.cjs...
created ./webpack/svelte-intl-loader.cjs in 123ms
Built template.html in 1716.28ms
$ cross-env PORT=22939 WEBPACK_CONFIG_FILE=webpack/webpack.config.cjs SERVER_FILE_EXT=cjs node ./node_modules/sapper/sapper export
> Building...
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:130:10)
    at BulkUpdateDecorator.hashFactory (/app/node_modules/webpack/lib/util/createHash.js:145:18)
    at BulkUpdateDecorator.update (/app/node_modules/webpack/lib/util/createHash.js:46:50)
    at OriginalSource.updateHash (/app/node_modules/webpack-sources/lib/OriginalSource.js:104:8)
    at NormalModule._initBuildHash (/app/node_modules/webpack/lib/NormalModule.js:868:17)
    at handleParseResult (/app/node_modules/webpack/lib/NormalModule.js:934:10)
    at /app/node_modules/webpack/lib/NormalModule.js:1026:4
    at processResult (/app/node_modules/webpack/lib/NormalModule.js:743:11)
    at /app/node_modules/webpack/lib/NormalModule.js:807:5
$ node bin/build-vercel-json.js
node:internal/errors:464
    ErrorCaptureStackTrace(err);
    ^

Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/app/__sapper__/service-worker.js' imported from /app/bin/build-vercel-json.js
    at new NodeError (node:internal/errors:371:5)
    at finalizeResolution (node:internal/modules/esm/resolve:394:11)
    at moduleResolve (node:internal/modules/esm/resolve:915:10)
    at defaultResolve (node:internal/modules/esm/resolve:1005:11)
    at ESMLoader.resolve (node:internal/modules/esm/loader:530:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:251:18)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:79:40)
    at link (node:internal/modules/esm/module_job:78:36) {
  code: 'ERR_MODULE_NOT_FOUND'
}

Node.js v17.3.0
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
ERROR: "build-vercel-json" exited with 1.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
ERROR: "build-steps" exited with 1.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
The command '/bin/sh -c yarn --production --pure-lockfile &&     yarn build &&     yarn cache clean &&     rm -rf ./src ./docs ./tests ./bin' returned a non-zero code: 1
ERROR: Service 'pinafore' failed to build : Build failed
```

**Comment by nolanlawson** [comment]
Error: error:0308010C:digital envelope routines::unsupported

Looks like your environment may not support a certain hash function? Does this only repro with a certain Node version on certain hardware?

**Comment by k3tan172** [comment]
I'm not sure, I'm just using the `docker-compose up --build -d` command. I downloaded and installed docker and docker-compose on a fresh install of Ubuntu 20.04. It worked when I built 2.0.0, but now I'm trying to upgrade to 2.0.2 and it's not working. Maybe some default dependencies have changed?

**Comment by nolanlawson** [comment]
Hm, I don't really know how Docker works, and the Dockerfile was contributed by other people. Could you test on some different hardware and see if it's hardware-related?

**Comment by k3tan172** [comment]
Thanks, appreciate the response. I think it has something to do with this. People are having issues in docker containers because of it. I'm fairly sure this isn't hardware related.
https://stackoverflow.com/questions/69692842/error-message-error0308010cdigital-envelope-routinesunsupported

**Comment by k3tan172** [comment]
Ok, I've figured it out. The Dockerfile needs to be amended with `ENV NODE_OPTIONS=--openssl-legacy-provider`
The Dockerfile should look like this:
```
# Using Alpine to keep the images smaller
# Change to using the official NodeJS Alpine container
FROM node:alpine

# Pushing all files into image
WORKDIR /app
COPY . /app

# Install Pinafore
ENV NODE_OPTIONS=--openssl-legacy-provider
RUN yarn --production --pure-lockfile && \
    yarn build && \
    yarn cache clean && \
    rm -rf ./src ./docs ./tests ./bin

# Expose port 4002
EXPOSE 4002

# Setting run-command, using explicit `node` command
# rather than `yarn` or `npm` to use less memory
# https://github.com/nolanlawson/pinafore/issues/971
CMD PORT=4002 node server.js
```

**Comment by nolanlawson** [comment]
I googled this, and it looks like a general Webpack issue with Node 17: https://github.com/webpack/webpack/issues/14532
