### ISSUE TITLE
docker build fails with latest version of node image

### ISSUE THREAD

**Issue by z-bsod** [nolanlawson/pinafore#2110]
Hello,

when trying to build a docker-container with the included Dockerfile from the 2.0.5 tag I had the build failing with the following error message:

```
$ cross-env PORT=22939 WEBPACK_CONFIG_FILE=webpack/webpack.config.cjs SERVER_FILE_EXT=cjs node ./node_modules/sapper/sapper export
> Building...
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:135:10)
    at BulkUpdateDecorator.hashFactory (/app/node_modules/webpack/lib/util/createHash.js:145:18)
    at BulkUpdateDecorator.update (/app/node_modules/webpack/lib/util/createHash.js:46:50)
    at OriginalSource.updateHash (/app/node_modules/webpack-sources/lib/OriginalSource.js:104:8)
    at NormalModule._initBuildHash (/app/node_modules/webpack/lib/NormalModule.js:868:17)
    at handleParseResult (/app/node_modules/webpack/lib/NormalModule.js:934:10)
    at /app/node_modules/webpack/lib/NormalModule.js:1026:4
    at processResult (/app/node_modules/webpack/lib/NormalModule.js:743:11)
    at /app/node_modules/webpack/lib/NormalModule.js:807:5
$ node bin/build-vercel-json.js
node:internal/errors:464
    ErrorCaptureStackTrace(err);
    ^

Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/app/__sapper__/service-worker.js' imported from /app/bin/build-vercel-json.js
    at new NodeError (node:internal/errors:371:5)
    at finalizeResolution (node:internal/modules/esm/resolve:394:11)
    at moduleResolve (node:internal/modules/esm/resolve:946:10)
    at defaultResolve (node:internal/modules/esm/resolve:1043:11)
    at ESMLoader.resolve (node:internal/modules/esm/loader:530:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:251:18)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:79:40)
    at link (node:internal/modules/esm/module_job:78:36) {
  code: 'ERR_MODULE_NOT_FOUND'
}

Node.js v17.5.0
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
ERROR: "build-vercel-json" exited with 1.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
ERROR: "build-steps" exited with 1.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
ERROR: Service 'pinafore' failed to build: The command '/bin/sh -c yarn --production --pure-lockfile &&     yarn build &&     yarn cache clean &&     rm -rf ./src ./docs ./tests ./bin' returned a non-zero code: 1
```

as far as I could see from the linked CI logs the builds and tests are still running on a node version 12 so I tried downgrading the used source image in the Dockerfile.

It seems to be building fine with versions up to 16 fails on 17 (which the node:alpine tag points to currently).

After the following change to the Dockerfile it was building fine for me again and seems to be working normally:

```diff
diff --git a/Dockerfile b/Dockerfile
index ccb12f6f..7a3a88ee 100644
--- a/Dockerfile
+++ b/Dockerfile
@@ -1,6 +1,6 @@
 # Using Alpine to keep the images smaller
 # Change to using the official NodeJS Alpine container
-FROM node:alpine
+FROM node:16-alpine

 # Pushing all files into image
 WORKDIR /ap
```

is this considered a valid fix from your side (I'd submit a PR in this case) or would you rather like to make modifications to the application to make it compatible to node17 instead?

For now, I hope this information is at least useful in case someone stumbles over the same issue.

**Comment by nolanlawson** [comment]
Thanks for the report. The odd-numbered versions of Node are typically considered beta-ish whereas the even-numbered ones are LTS. So supporting Node 16 in the Dockerfile is fine, but for 17, we may want to just wait for 18 to be released.
