### ISSUE TITLE
build fails with node 18

### ISSUE THREAD

**Issue by abochmann** [nolanlawson/pinafore#2165]
I was trying to upgrade from an older release to node.js 18, which is currently LTS, but ran into a build error - see below. Rolling back to 16 (also still supported) solves the problem for now.

I get:

```
$ cross-env PORT=22939 WEBPACK_CONFIG_FILE=webpack/webpack.config.cjs SERVER_FILE_EXT=cjs node ./node_modules/sapper/sapper export
> Building...
assets by status 1.24 MiB [cached] 99 assets
orphan modules 1.4 MiB [orphan] 438 modules
runtime modules 11 KiB 11 modules
built modules 2.55 MiB [built]
  modules by path ./src/ 1.84 MiB 209 modules
  modules by path ./node_modules/ 667 KiB
    modules by path ./node_modules/@formatjs/ 313 KiB 45 modules
    modules by path ./node_modules/tesseract.js/ 14.5 KiB 19 modules
    modules by path ./node_modules/blueimp-load-image/js/*.js 65.2 KiB 10 modules
    modules by path ./node_modules/svelte/*.js 27.9 KiB 2 modules
    modules by path ./node_modules/@stdlib/utils-noop/lib/*.js 1.62 KiB 2 modules
    modules by path ./node_modules/emoji-picker-element/*.js 116 KiB 2 modules
    + 23 modules
  ./__sapper__/client.js + 7 modules 59.5 KiB [built] [code generated]

ERROR in ./node_modules/tesseract.js-core/tesseract-core.wasm.js
Module build failed (from ./node_modules/file-loader/dist/cjs.js):
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at getHashDigest (/home/pinafore/pinafore/node_modules/loader-utils/lib/getHashDigest.js:46:34)
    at /home/pinafore/pinafore/node_modules/loader-utils/lib/interpolateName.js:113:11
    at String.replace (<anonymous>)
    at interpolateName (/home/pinafore/pinafore/node_modules/loader-utils/lib/interpolateName.js:110:8)
    at Object.loader (/home/pinafore/pinafore/node_modules/file-loader/dist/index.js:29:48)
 @ ./src/routes/_utils/tesseractWorker.js 5:0-63 14:25-33
 @ ./src/routes/_utils/asyncModules/importTesseractWorker.js 1:43-3:1
 @ ./src/routes/_utils/runTesseract.js 1:0-87 42:20-41
 @ ./src/routes/_components/dialog/components/MediaAltEditor.html 14:0-62 116:23-35 121:21-33
 @ ./src/routes/_components/dialog/components/MediaEditDialog.html 8:0-62 49:26-40
 @ ./src/routes/_components/dialog/creators/showMediaEditDialog.js 1:0-70 5:20-41
 @ ./src/routes/_components/dialog/asyncDialogs/importShowMediaEditDialog.js
 @ ./src/routes/_components/compose/ComposeMediaItem.html 12:0-95 91:38-63
 @ ./src/routes/_components/compose/ComposeMedia.html 4:0-54 165:28-44
 @ ./src/routes/_components/compose/ComposeBox.html 9:0-46 289:24-36
 @ ./src/routes/_utils/asyncModules/importComposeBox.js
 @ ./src/routes/_components/compose/LazyComposeBox.html 3:0-80 16:4-20
 @ ./src/routes/_components/TimelineHomePage.html 6:0-58 42:26-40
 @ ./src/routes/_pages/index.html 5:0-67 98:28-44
 @ ./src/routes/index.html 5:0-47 11:2-15
 @ ./__sapper__/client.js
 @ ./src/client.js

ERROR in ./node_modules/tesseract.js/dist/worker.min.js
Module build failed (from ./node_modules/file-loader/dist/cjs.js):
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at getHashDigest (/home/pinafore/pinafore/node_modules/loader-utils/lib/getHashDigest.js:46:34)
    at /home/pinafore/pinafore/node_modules/loader-utils/lib/interpolateName.js:113:11
    at String.replace (<anonymous>)
    at interpolateName (/home/pinafore/pinafore/node_modules/loader-utils/lib/interpolateName.js:110:8)
    at Object.loader (/home/pinafore/pinafore/node_modules/file-loader/dist/index.js:29:48)
 @ ./src/routes/_utils/tesseractWorker.js 6:0-56 12:27-37
 @ ./src/routes/_utils/asyncModules/importTesseractWorker.js 1:43-3:1
 @ ./src/routes/_utils/runTesseract.js 1:0-87 42:20-41
 @ ./src/routes/_components/dialog/components/MediaAltEditor.html 14:0-62 116:23-35 121:21-33
 @ ./src/routes/_components/dialog/components/MediaEditDialog.html 8:0-62 49:26-40
 @ ./src/routes/_components/dialog/creators/showMediaEditDialog.js 1:0-70 5:20-41
 @ ./src/routes/_components/dialog/asyncDialogs/importShowMediaEditDialog.js
 @ ./src/routes/_components/compose/ComposeMediaItem.html 12:0-95 91:38-63
 @ ./src/routes/_components/compose/ComposeMedia.html 4:0-54 165:28-44
 @ ./src/routes/_components/compose/ComposeBox.html 9:0-46 289:24-36
 @ ./src/routes/_utils/asyncModules/importComposeBox.js
 @ ./src/routes/_components/compose/LazyComposeBox.html 3:0-80 16:4-20
 @ ./src/routes/_components/TimelineHomePage.html 6:0-58 42:26-40
 @ ./src/routes/_pages/index.html 5:0-67 98:28-44
 @ ./src/routes/index.html 5:0-47 11:2-15
 @ ./__sapper__/client.js
 @ ./src/client.js

webpack 5.69.1 compiled with 2 errors in 33177 ms
> Encountered errors while building app
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
ERROR: "sapper-export" exited with 1.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
ERROR: "build-steps" exited with 1.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by abochmann** [comment]
Oh, sorry, didn't see that in there. I'm on a Debian 11/bullseye system, which is still using openssl 1.1.1

I'll retry in a couple of days with that thread in mind, but since this doesn't seem to be a Pinafore problem, it's probably safe to close this issue?
