### ISSUE TITLE
Errors building. Pre-built version available?

### ISSUE THREAD

**Issue by edent** [nolanlawson/pinafore#2186]
(This is my first time trying to deploy a node app to my host - feel free to treat me like a small child in your reply!)

When I run `yarn build`, I get an error "Cannot allocate memory".

```
yarn run v1.22.19
warning ../package.json: No license field
$ cross-env NODE_ENV=production run-s build-steps
warning ../package.json: No license field
$ run-s before-build sapper-export build-vercel-json
warning ../package.json: No license field
$ run-p build-template-html build-assets build-webpack-config
warning ../package.json: No license field
$ node ./bin/build-assets.js
warning ../package.json: No license field
/home/user/nodevenv/pinafore/16/bin/node: fork: Cannot allocate memory
$ rollup -c ./webpack/rollup.config.js
error Command failed with exit code 254.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
ERROR: "build-assets" exited with 254.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
ERROR: "before-build" exited with 1.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
ERROR: "build-steps" exited with 1.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

The the suggestion of a random StackOverflow post, I did `npm cache clean --force`.  That gets a bit further, but then dies with:

```
Error: spawn ENOMEM
    at ChildProcess.spawn (node:internal/child_process:413:11)
    at spawn (node:child_process:713:9)
    at fork (node:child_process:167:10)
    at ChildProcessWorker.initialize (/home/user/pinafore/pinafore-2.2.3/node_modules/jest-worker/build/workers/ChildProcessWorker.js:141:45)
    at new ChildProcessWorker (/home/user/pinafore/pinafore-2.2.3/node_modules/jest-worker/build/workers/ChildProcessWorker.js:132:10)
    at WorkerPool.createWorker (/home/user/pinafore/pinafore-2.2.3/node_modules/jest-worker/build/WorkerPool.js:44:12)
    at new BaseWorkerPool (/home/user/pinafore/pinafore-2.2.3/node_modules/jest-worker/build/base/BaseWorkerPool.js:135:27)
    at new WorkerPool (/home/user/pinafore/pinafore-2.2.3/node_modules/jest-worker/build/WorkerPool.js:30:1)
    at new JestWorker (/home/user/pinafore/pinafore-2.2.3/node_modules/jest-worker/build/index.js:151:26)
    at Object.renderChunk (/home/user/pinafore/pinafore-2.2.3/node_modules/rollup-plugin-terser/rollup-plugin-terser.js:22:23) {
  errno: -12,
  code: 'PLUGIN_ERROR',
  syscall: 'spawn',
  pluginCode: 'ENOMEM',
  plugin: 'terser',
  hook: 'renderChunk'
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
ERROR: "build-template-html" exited with 1.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
ERROR: "before-build" exited with 1.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
ERROR: "build-steps" exited with 1.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

And now I'm  a bit stuck.  Is there a pre-built package that I can just drop onto my host?

Love the app, runs really well on my low-powered phone.

**Comment by nolanlawson** [comment]
There is no prebuilt version, sorry. It looks like the machine you're using to build it cannot handle the amount of memory that Webpack wants to allocate. :confused:

Best bet in this case would probably be to build it on a machine with more memory, and then copy the files over to the machine with less memory.

I could give you prebuilt files, but they would quickly get out of date, and I don't plan on publishing the prebuilt files for every release. :slightly_smiling_face: 

Are you using Node v12 and yarn v1? That's what is currently used in CI.
