### ISSUE TITLE
dev.pinafore.social deployments from Travis are broken

### ISSUE THREAD

**Issue by nolanlawson** [nolanlawson/pinafore#342]
Not sure when this happened, but there are errors like [this one](https://travis-ci.org/nolanlawson/pinafore/jobs/384225732) showing:

```
https://pinafore-vwsgbhpoxm.now.sh> Buildingâ€¦
> â–² npm install
> âœ“ Using "package-lock.json"
> â§— Installing 49 main dependenciesâ€¦
> âœ“ Installed 1424 modules [11s]
> â–² npm run build
> 
> pinafore@0.5.0 build /home/nowuser/src
> cross-env NODE_ENV=production npm run build-steps
> 
> 
> pinafore@0.5.0 build-steps /home/nowuser/src
> run-s globalize-css build-sass build-svg build-inline-script sapper-build deglobalize-css
> 
> 
> pinafore@0.5.0 globalize-css /home/nowuser/src
> node ./bin/globalize-css.js
> 
> 
> pinafore@0.5.0 build-sass /home/nowuser/src
> node ./bin/build-sass.js
> 
>       throw new Error(errors.missingBinary());
> /home/nowuser/src/node_modules/node-sass/lib/binding.js:15
>       ^
> 
> Error: Missing binding /home/nowuser/src/node_modules/node-sass/vendor/linux_musl-x64-64/binding.node
> Node Sass could not find a binding for your current environment: Linux/musl 64-bit with Node.js 10.x
> 
> Found bindings for the following environments:
>   - Linux/musl 64-bit with Node.js 8.x
> 
> This usually happens because your environment has changed since running `npm install`.
> Run `npm rebuild node-sass --force` to build the binding for your current environment.
>     at module.exports (/home/nowuser/src/node_modules/node-sass/lib/binding.js:15:13)
>     at Object.<anonymous> (/home/nowuser/src/node_modules/node-sass/lib/index.js:14:35)
>     at Module._compile (internal/modules/cjs/loader.js:678:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
>     at Module.load (internal/modules/cjs/loader.js:589:32)
>     at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
>     at Function.Module._load (internal/modules/cjs/loader.js:520:3)
>     at Module.require (internal/modules/cjs/loader.js:626:17)
>     at require (internal/modules/cjs/helpers.js:20:18)
>     at Object.<anonymous> (/home/nowuser/src/bin/build-sass.js:3:14)
```

**Comment by nolanlawson** [comment]
confirmed fixed https://travis-ci.org/nolanlawson/pinafore/jobs/384793398
