### ISSUE TITLE
Docker will not build

### ISSUE THREAD

**Issue by usbsnowcrash** [nolanlawson/pinafore#413]
I have the latest code from master on my server and I get the following error when I try to docker build.
```
Step 5/10 : RUN apk add nodejs git python build-base clang
 ---> Using cache
 ---> 8ad0ea5ee565
Step 6/10 : RUN npm i npm@latest -g
 ---> Using cache
 ---> 5c368c9234f1
Step 7/10 : RUN npm install
 ---> Running in 32e889505ac2
module.js:538
    throw err;
    ^

Error: Cannot find module 'npmlog'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at /usr/lib/node_modules/npm/bin/npm-cli.js:22:13
    at Object.<anonymous> (/usr/lib/node_modules/npm/bin/npm-cli.js:145:3)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
The command '/bin/sh -c npm install' returned a non-zero code: 1
```

**Comment by nolanlawson** [comment]
Which operating system is this on?
