### ISSUE TITLE
Problems installing 0.9.0

### ISSUE THREAD

**Issue by jeroenpraat** [nolanlawson/pinafore#547]
I stopped Pinafora first, than I do in the pinafora directory (as an user, not as root):

npm install

```
audited 14715 packages in 16.354s
found 13 vulnerabilities (2 low, 9 moderate, 2 high)
  run `npm audit fix` to fix them, or `npm audit` for details
```
Whatever I do (nothing or 'npm audit fix') I get this when I do:

npm run build

```
> pinafore@0.8.3 build /home/jeroen/www/pinafore
> cross-env NODE_ENV=production npm run build-steps

sh: 1: cross-env: not found
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! pinafore@0.8.3 build: `cross-env NODE_ENV=production npm run build-steps`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the pinafore@0.8.3 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/jeroen/.npm/_logs/2018-09-17T17_32_19_519Z-debug.log
```

**Comment by jeroenpraat** [comment]
Here is the mentioned log file:

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'build' ]
2 info using npm@6.4.1
3 info using node@v8.12.0
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle pinafore@0.8.3~prebuild: pinafore@0.8.3
6 info lifecycle pinafore@0.8.3~build: pinafore@0.8.3
7 verbose lifecycle pinafore@0.8.3~build: unsafe-perm in lifecycle true
8 verbose lifecycle pinafore@0.8.3~build: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:
/home/jeroen/www/pinafore/node_modules/.bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games
9 verbose lifecycle pinafore@0.8.3~build: CWD: /home/jeroen/www/pinafore
10 silly lifecycle pinafore@0.8.3~build: Args: [ '-c', 'cross-env NODE_ENV=production npm run build-steps' ]
11 info lifecycle pinafore@0.8.3~build: Failed to exec build script
12 verbose stack Error: pinafore@0.8.3 build: `cross-env NODE_ENV=production npm run build-steps`
12 verbose stack spawn ENOENT
12 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.j
s:48:18)
12 verbose stack     at emitTwo (events.js:126:13)
12 verbose stack     at ChildProcess.emit (events.js:214:7)
12 verbose stack     at maybeClose (internal/child_process.js:915:16)
12 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
13 verbose pkgid pinafore@0.8.3
14 verbose cwd /home/jeroen/www/pinafore
15 verbose Linux 4.9.0-8-amd64
16 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "build"
17 verbose node v8.12.0
18 verbose npm  v6.4.1
19 error file sh
20 error code ELIFECYCLE
21 error errno ENOENT
22 error syscall spawn
23 error pinafore@0.8.3 build: `cross-env NODE_ENV=production npm run build-steps`
23 error spawn ENOENT
24 error Failed at the pinafore@0.8.3 build script.
24 error This is probably not a problem with npm. There is likely additional logging output above.
25 verbose exit [ 1, true ]
```

**Comment by jeroenpraat** [comment]
npm --version
6.4.1

**Comment by jeroenpraat** [comment]
I cloned a clean directory and still a problem. Now I get this output:

npm install

```
npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://npm.community>

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/jeroen/.npm/_logs/2018-09-17T18_08_40_284Z-debug.log

```

npm --version
6.4.1

**Comment by jeroenpraat** [comment]
I restored the 0.8.2 backup and still I get the above error. I also tried t clean the cache. It's all useless.

**Comment by jeroenpraat** [comment]
Maybe related: 

https://npm.community/t/crash-npm-err-cb-never-called/858

**Comment by jeroenpraat** [comment]
After downgrading nodejs 8.12.0 (with npm 6.4.1) to the previous nodejs version 8.11.4 (with npm 5.6.0) everything works. 

Maybe temporary put a max. npm version in the README will help others as well @nolanlawson .

Closing now.

**Comment by jeroenpraat** [comment]
Same issue with upgrading to 0.9.0 with a freshly cloned install.

```
$ which npm
/usr/bin/npm
$ npm -v
6.4.1
$ npm install
npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://npm.community>

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/jeroen/.npm/_logs/2018-09-27T16_33_35_436Z-debug.log
```

Reopening

**Comment by jeroenpraat** [comment]
@nolanlawson FYI:

I clones Pinafora on another VPS (also Debian 9) and I have exactly the same problem. So it's not an upgrade problem, but an install problem.

node -v
v8.12.0

npm -v
6.4.1

**Comment by jeroenpraat** [comment]
Fixed! Sorry, it was not related to Pinafore. I had the pinafore directory in a fuse mounted location. NPM doesn't like that.
