### ISSUE TITLE
npm run build yields TypeError in 0.17.0

### ISSUE THREAD

**Issue by Shadow8t4** [nolanlawson/pinafore#911]
I've been self-hosting Pinafore on Ubuntu Server 18.04, npm is the requested version, npm install runs just fine. I haven't modified anything other than inserting an custom theme as part of the list of themes, and 0.16.0 runs fine, which is what I'm currently stuck on for now.

Here's an output of npm run build:

```
$ npm run build

> pinafore@0.17.0 build /home/mastodon/pinafore
> cross-env NODE_ENV=production npm run build-steps


> pinafore@0.17.0 build-steps /home/mastodon/pinafore
> run-s before-build sapper-build


> pinafore@0.17.0 before-build /home/mastodon/pinafore
> run-s build-template-html build-third-party-assets


> pinafore@0.17.0 build-template-html /home/mastodon/pinafore
> node -r esm ./bin/build-template-html.js

TypeError: Cannot read property '0' of undefined
    at Object.buildInlineScript [as rebuild] (/home/mastodon/pinafore/bin/build-inline-script.js:36:29)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:229:7)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! pinafore@0.17.0 build-template-html: `node -r esm ./bin/build-template-html.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the pinafore@0.17.0 build-template-html script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/mastodon/.npm/_logs/2019-01-20T23_57_52_735Z-debug.log
ERROR: "build-template-html" exited with 1.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! pinafore@0.17.0 before-build: `run-s build-template-html build-third-party-assets`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the pinafore@0.17.0 before-build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/mastodon/.npm/_logs/2019-01-20T23_57_52_844Z-debug.log
ERROR: "before-build" exited with 1.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! pinafore@0.17.0 build-steps: `run-s before-build sapper-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the pinafore@0.17.0 build-steps script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/mastodon/.npm/_logs/2019-01-20T23_57_52_886Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! pinafore@0.17.0 build: `cross-env NODE_ENV=production npm run build-steps`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the pinafore@0.17.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/mastodon/.npm/_logs/2019-01-20T23_57_52_931Z-debug.log
 ```

I'll be happy to provide the log files if necessary, currently not home so I can't access them atm (I've lost ssh access since this error, not caused by it).

**Comment by nolanlawson** [comment]
Thanks for reporting, this looks like an issue with Rollup, which I believed changed in v1.0.0 so that it returned an array rather than an object from the `bundle.generate()` function.

Did you run `npm install` prior to `npm run build`? You may also need to upgrade npm (`npm install --global npm`) and/or Node (I typically test on v10, but v8 should be supported). You may also need to `rm -fr node_modules && npm install` if something really strange is up.

**Comment by nolanlawson** [comment]
Closing, please reopen if this is still an issue. Also note that we're using `yarn` now instead of `npm`, also Node v8+ is supported.
